kind: Service
apiVersion: v1
metadata:
  name: hedera-records-server
  labels:
    app: hedera-records-server
spec:
  type: NodePort
  selector:
    app: hedera-records-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---

