### BALANCES
### get balances default
GET http://localhost:8080/api/v1/balances
Accept: application/json
### get balances for account 5
GET http://localhost:8080/api/v1/balances?account.id=5
Accept: application/json
### get balances for account 0.0.5
GET http://localhost:8080/api/v1/balances?account.id=0.0.5
Accept: application/json
### get balances for account > 10,000
GET http://localhost:8080/api/v1/balances?account.id=gt:0.0.10000&limit=100
Accept: application/json
### get balances for account > 700,000
GET http://localhost:8080/api/v1/balances?account.id=gt:0.0.700000&limit=100
Accept: application/json

### BLOCKS
### get blocks default
GET http://localhost:8080/api/v1/blocks
Accept: application/json
### get block 125
GET http://localhost:8080/api/v1/blocks?block.number=125
Accept: application/json
### get block > 1000
GET http://localhost:8080/api/v1/blocks?block.number=gt:1000
Accept: application/json
### get blocks desc order
GET http://localhost:8080/api/v1/blocks?order=desc
Accept: application/json
### get blocks desc order limit 5
GET http://localhost:8080/api/v1/blocks?order=desc&limit=5
Accept: application/json

### TOKENS
### get tokens default
GET http://localhost:8080/api/v1/tokens
Accept: application/json
### get token public key 9e3359cb5a484e7dd942559b50fda3da70cda4935e7e12cfd56d5dc5c67f96d7
GET http://localhost:8080/api/v1/tokens?publickey=9e3359cb5a484e7dd942559b50fda3da70cda4935e7e12cfd56d5dc5c67f96d7
Accept: application/json
### get token entity 107594 (this returns two elements)
GET http://localhost:8080/api/v1/tokens?token.id=107594
Accept: application/json
### get token > 1000
GET http://localhost:8080/api/v1/tokens?token.id=gt:1000
### get only fungible tokens
GET http://localhost:8080/api/v1/tokens?type=FUNGIBLE_COMMON
Accept: application/json
### get only non-fungible tokens
GET http://localhost:8080/api/v1/tokens?type=NON_FUNGIBLE_UNIQUE
Accept: application/json
### get all types of tokens
GET http://localhost:8080/api/v1/tokens?type=ALL
Accept: application/json
### get tokens from (autoRenew) Account id 950
GET http://localhost:8080/api/v1/tokens?account.id=950
Accept: application/json
### get tokens desc order
GET http://localhost:8080/api/v1/tokens?order=desc
Accept: application/json
### get tokens desc order limit 5
GET http://localhost:8080/api/v1/tokens?order=desc&limit=5
Accept: application/json
###
### getTokenById not specifying a timestamp
GET http://localhost:8080/api/v1/tokens/107594
### getTokenById specifying a timestamp
GET http://localhost:8080/api/v1/tokens/107594?timestamp=1610640452612903002
### getTokenById specifying an earlier timestamp
GET http://localhost:8080/api/v1/tokens/107594?timestamp=1610640421985772001
### getTokenById specifying an earlier timestamp than the passed-in one
GET http://localhost:8080/api/v1/tokens/107594?timestamp=lt:1610640452612903002
###
### listTokenBalancesById specifying only a token id
GET http://localhost:8080/api/v1/tokens/629591/balances?limit=99
### listTokenBalancesById specifying a token id and an account id
GET http://localhost:8080/api/v1/tokens/629591/balances?account.id=644972
### listTokenBalancesById specifying a token id and a range of account ids
GET http://localhost:8080/api/v1/tokens/629591/balances?account.id=gt:644000&account.id=lt:644999&limit=1000
### listTokenBalancesById specifying a token id and a range of account ids, sorted in descending order
GET http://localhost:8080/api/v1/tokens/629591/balances?account.id=gt:644000&account.id=lt:644999&limit=1000&order=desc
### listTokenBalancesById specifying a token id and an account id and a particular balance amount
GET http://localhost:8080/api/v1/tokens/629591/balances?account.id=644972&account.balance=500000000
### listTokenBalancesById specifying a token id and an account id and a particular timestamp -- not yet working
GET http://localhost:8080/api/v1/tokens/629591/balances?account.id=644972&timestamp=1644887406787336960

### TRANSACTIONS
### get transactions by Id
GET http://localhost:8080/api/v1/transactions/0.0.89748-1612413398-472232185
Accept: application/json
### get transactions by Id filter by nonce and scheduled
GET http://localhost:8080/api/v1/transactions/0.0.89748-1612413398-472232185?nonce=0&scheduled=false
Accept: application/json
### get transactions by accountId
GET http://localhost:8080/api/v1/transactions?account.id=969040&limit=10&order=asc&transactiontype=CRYPTOTRANSFER
Accept: application/json
### get transactions by CREDIT type
GET http://localhost:8080/api/v1/transactions?account.id=98&limit=200&order=asc&type=CREDIT
Accept: application/json
### get transactions by DEBIT type
GET http://localhost:8080/api/v1/transactions?account.id=100&limit=2&order=asc&type=DEBIT
Accept: application/json


### ACCOUNTS
### get accounts by Id
GET http://localhost:8080/api/v1/accounts/969040
Accept: application/json
### get accounts by Id and transaction type
GET http://localhost:8080/api/v1/accounts/969040?transactiontype=CRYPTOTRANSFER
Accept: application/json
### get accounts by alias and transaction type
GET http://localhost:8080/api/v1/accounts/ac384c53f03855fa1b3616052f8ba32c6c2a2fec?transactiontype=CRYPTOTRANSFER
Accept: application/json

### get nfts for an account id
GET http://localhost:8080/api/v1/accounts/0/nfts
Accept: application/json

### get nfts for an account id with filters
GET http://localhost:8080/api/v1/accounts/0/nfts?deleted=false&serial_number=1871&token_id=1066828&limit=10&order=asc
Accept: application/json
